// Sample NFT data for display when database is not connected
export interface SampleNFT {
  id: string;
  title: string;
  description: string;
  mediaUrl: string;
  mediaType: 'image' | 'video' | 'audio' | 'other';
  price: number;
  category: string;
  tags: string[];
  creatorName: string;
  creatorUsername: string;
  creatorAvatar: string;
  ownerName: string;
  ownerUsername: string;
  ownerAvatar: string;
  likes: number;
  views: number;
}

// Helper to generate random stats
const randomLikes = () => Math.floor(Math.random() * 500) + 50;
const randomViews = () => Math.floor(Math.random() * 5000) + 500;

// Creator profiles
const creators = [
  { name: 'Astrid Nova', username: 'astridnova', avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop' },
  { name: 'Marcus Chen', username: 'marcuschen', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop' },
  { name: 'Luna Eclipse', username: 'lunaeclipse', avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop' },
  { name: 'Kai Rodriguez', username: 'kairodriguez', avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop' },
  { name: 'Zara Mitchell', username: 'zaramitchell', avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop' },
  { name: 'Neo Digital', username: 'neodigital', avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop' },
  { name: 'Aria Storm', username: 'ariastorm', avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop' },
  { name: 'Rex Phantom', username: 'rexphantom', avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&h=150&fit=crop' },
];

const getCreator = (index: number) => creators[index % creators.length]!;

export const sampleNFTs: SampleNFT[] = [
  // ============ DIGITAL ART (18 items) ============
  {
    id: 'nft-001',
    title: 'Cosmic Dreamscape #001',
    description: 'A mesmerizing journey through the cosmos, featuring vibrant nebulae and distant galaxies.',
    mediaUrl: 'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=800&q=80',
    mediaType: 'image',
    price: 2.5,
    category: 'digital-art',
    tags: ['space', 'cosmic', 'abstract', 'nebula'],
    ...(() => { const c = getCreator(0); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-002',
    title: 'Neon Dreams Collection',
    description: 'Abstract digital art piece featuring flowing neon colors and geometric patterns.',
    mediaUrl: 'https://images.unsplash.com/photo-1550684376-efcbd6e3f031?w=800&q=80',
    mediaType: 'image',
    price: 3.7,
    category: 'digital-art',
    tags: ['neon', 'abstract', 'geometric', 'vibrant'],
    ...(() => { const c = getCreator(1); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-003',
    title: 'Retro Synthwave Scene',
    description: 'A nostalgic trip to the 80s with this synthwave-inspired digital artwork.',
    mediaUrl: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=800&q=80',
    mediaType: 'image',
    price: 1.8,
    category: 'digital-art',
    tags: ['synthwave', 'retro', '80s', 'neon'],
    ...(() => { const c = getCreator(2); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-004',
    title: 'Digital Fluid Art #12',
    description: 'Mesmerizing fluid simulation captured in stunning digital format.',
    mediaUrl: 'https://images.unsplash.com/photo-1567095761054-7a02e69e5c43?w=800&q=80',
    mediaType: 'image',
    price: 2.1,
    category: 'digital-art',
    tags: ['fluid', 'abstract', 'colorful', 'dynamic'],
    ...(() => { const c = getCreator(3); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-005',
    title: 'Fractal Universe',
    description: 'Infinite complexity captured in this stunning fractal artwork.',
    mediaUrl: 'https://images.unsplash.com/photo-1518640467707-6811f4a6ab73?w=800&q=80',
    mediaType: 'image',
    price: 4.2,
    category: 'digital-art',
    tags: ['fractal', 'mathematics', 'infinite', 'pattern'],
    ...(() => { const c = getCreator(4); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-006',
    title: 'Aurora Digital',
    description: 'Northern lights reimagined through digital artistry.',
    mediaUrl: 'https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=800&q=80',
    mediaType: 'image',
    price: 3.3,
    category: 'digital-art',
    tags: ['aurora', 'nature', 'lights', 'digital'],
    ...(() => { const c = getCreator(5); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-007',
    title: 'Geometric Illusion',
    description: 'Mind-bending geometric patterns that challenge perception.',
    mediaUrl: 'https://images.unsplash.com/photo-1558591710-4b4a1ae0f04d?w=800&q=80',
    mediaType: 'image',
    price: 1.5,
    category: 'digital-art',
    tags: ['geometric', 'illusion', 'abstract', 'pattern'],
    ...(() => { const c = getCreator(6); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-008',
    title: 'Cyberpunk Cityscape',
    description: 'Futuristic city bathed in neon lights and rain.',
    mediaUrl: 'https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?w=800&q=80',
    mediaType: 'image',
    price: 5.5,
    category: 'digital-art',
    tags: ['cyberpunk', 'city', 'neon', 'future'],
    ...(() => { const c = getCreator(7); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-009',
    title: 'Holographic Dreams',
    description: 'Iridescent holographic art piece with shifting colors.',
    mediaUrl: 'https://images.unsplash.com/photo-1557672172-298e090bd0f1?w=800&q=80',
    mediaType: 'image',
    price: 2.8,
    category: 'digital-art',
    tags: ['holographic', 'iridescent', 'abstract', 'colorful'],
    ...(() => { const c = getCreator(0); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-010',
    title: 'Digital Bloom',
    description: 'Abstract floral patterns in vivid digital colors.',
    mediaUrl: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&q=80',
    mediaType: 'image',
    price: 1.9,
    category: 'digital-art',
    tags: ['floral', 'abstract', 'bloom', 'nature'],
    ...(() => { const c = getCreator(1); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-011',
    title: 'Vaporwave Sunset',
    description: 'Retro-futuristic sunset scene in classic vaporwave style.',
    mediaUrl: 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?w=800&q=80',
    mediaType: 'image',
    price: 2.2,
    category: 'digital-art',
    tags: ['vaporwave', 'sunset', 'retro', 'aesthetic'],
    ...(() => { const c = getCreator(2); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-012',
    title: 'Particle Storm',
    description: 'Dynamic particle simulation frozen in time.',
    mediaUrl: 'https://images.unsplash.com/photo-1534796636912-3b95b3ab5986?w=800&q=80',
    mediaType: 'image',
    price: 3.1,
    category: 'digital-art',
    tags: ['particles', 'dynamic', 'abstract', 'simulation'],
    ...(() => { const c = getCreator(3); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-013',
    title: 'Quantum Threads',
    description: 'Visualization of quantum entanglement in artistic form.',
    mediaUrl: 'https://images.unsplash.com/photo-1620641788421-7a1c342ea42e?w=800&q=80',
    mediaType: 'image',
    price: 4.8,
    category: 'digital-art',
    tags: ['quantum', 'science', 'abstract', 'threads'],
    ...(() => { const c = getCreator(4); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-014',
    title: 'Digital Marble',
    description: 'Luxurious marble textures reimagined digitally.',
    mediaUrl: 'https://images.unsplash.com/photo-1553356084-58ef4a67b2a7?w=800&q=80',
    mediaType: 'image',
    price: 1.6,
    category: 'digital-art',
    tags: ['marble', 'texture', 'luxury', 'abstract'],
    ...(() => { const c = getCreator(5); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-015',
    title: 'Glitch Art Series #7',
    description: 'Intentional digital corruption turned into art.',
    mediaUrl: 'https://images.unsplash.com/photo-1633467067670-e6e6e51d6a16?w=800&q=80',
    mediaType: 'image',
    price: 2.4,
    category: 'digital-art',
    tags: ['glitch', 'corruption', 'digital', 'experimental'],
    ...(() => { const c = getCreator(6); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-016',
    title: 'Prismatic Wave',
    description: 'Light refraction creating rainbow wave patterns.',
    mediaUrl: 'https://images.unsplash.com/photo-1557683316-973673baf926?w=800&q=80',
    mediaType: 'image',
    price: 3.5,
    category: 'digital-art',
    tags: ['prismatic', 'rainbow', 'wave', 'light'],
    ...(() => { const c = getCreator(7); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-017',
    title: 'Neural Network Art',
    description: 'AI-inspired visualization of neural connections.',
    mediaUrl: 'https://images.unsplash.com/photo-1614850523459-c2f4c699c52e?w=800&q=80',
    mediaType: 'image',
    price: 6.2,
    category: 'digital-art',
    tags: ['AI', 'neural', 'technology', 'futuristic'],
    ...(() => { const c = getCreator(0); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-018',
    title: 'Digital Sunset Waves',
    description: 'Serene digital interpretation of ocean sunset.',
    mediaUrl: 'https://images.unsplash.com/photo-1604076913837-52ab5629fba9?w=800&q=80',
    mediaType: 'image',
    price: 2.0,
    category: 'digital-art',
    tags: ['sunset', 'ocean', 'waves', 'serene'],
    ...(() => { const c = getCreator(1); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },

  // ============ PHOTOGRAPHY (16 items) ============
  {
    id: 'nft-019',
    title: 'Urban Decay Series #12',
    description: 'Street photography capturing the raw beauty of abandoned urban spaces.',
    mediaUrl: 'https://images.unsplash.com/photo-1518893494013-481c1d8ed3fd?w=800&q=80',
    mediaType: 'image',
    price: 0.8,
    category: 'photography',
    tags: ['urban', 'street', 'abandoned', 'architecture'],
    ...(() => { const c = getCreator(2); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-020',
    title: 'Midnight Ocean Waves',
    description: 'Long exposure photography of ocean waves under moonlight.',
    mediaUrl: 'https://images.unsplash.com/photo-1505118380757-91f5f5632de0?w=800&q=80',
    mediaType: 'image',
    price: 1.2,
    category: 'photography',
    tags: ['ocean', 'night', 'long-exposure', 'nature'],
    ...(() => { const c = getCreator(3); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-021',
    title: 'Ethereal Bloom',
    description: 'Macro photography of delicate flower petals with morning dew.',
    mediaUrl: 'https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=800&q=80',
    mediaType: 'image',
    price: 0.65,
    category: 'photography',
    tags: ['macro', 'flower', 'nature', 'dew'],
    ...(() => { const c = getCreator(4); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-022',
    title: 'City Lights After Rain',
    description: 'Urban night photography with reflections on wet streets.',
    mediaUrl: 'https://images.unsplash.com/photo-1519501025264-65ba15a82390?w=800&q=80',
    mediaType: 'image',
    price: 0.95,
    category: 'photography',
    tags: ['city', 'night', 'rain', 'reflections'],
    ...(() => { const c = getCreator(5); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-023',
    title: 'Mountain Majesty',
    description: 'Breathtaking landscape of snow-capped mountains at golden hour.',
    mediaUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80',
    mediaType: 'image',
    price: 1.8,
    category: 'photography',
    tags: ['mountains', 'landscape', 'nature', 'golden-hour'],
    ...(() => { const c = getCreator(6); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-024',
    title: 'Desert Dunes',
    description: 'Minimalist desert photography with dramatic shadows.',
    mediaUrl: 'https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=800&q=80',
    mediaType: 'image',
    price: 1.1,
    category: 'photography',
    tags: ['desert', 'minimal', 'shadows', 'nature'],
    ...(() => { const c = getCreator(7); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-025',
    title: 'Forest Whispers',
    description: 'Mystical forest scene with fog and sunbeams.',
    mediaUrl: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=800&q=80',
    mediaType: 'image',
    price: 1.4,
    category: 'photography',
    tags: ['forest', 'fog', 'mystical', 'nature'],
    ...(() => { const c = getCreator(0); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-026',
    title: 'Architectural Lines',
    description: 'Modern architecture with striking geometric lines.',
    mediaUrl: 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&q=80',
    mediaType: 'image',
    price: 0.9,
    category: 'photography',
    tags: ['architecture', 'geometric', 'modern', 'lines'],
    ...(() => { const c = getCreator(1); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-027',
    title: 'Northern Lights',
    description: 'Aurora borealis dancing over frozen landscape.',
    mediaUrl: 'https://images.unsplash.com/photo-1483347756197-71ef80e95f73?w=800&q=80',
    mediaType: 'image',
    price: 2.5,
    category: 'photography',
    tags: ['aurora', 'night', 'landscape', 'arctic'],
    ...(() => { const c = getCreator(2); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-028',
    title: 'Street Portrait',
    description: 'Candid street portrait with cinematic lighting.',
    mediaUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80',
    mediaType: 'image',
    price: 0.75,
    category: 'photography',
    tags: ['portrait', 'street', 'cinematic', 'people'],
    ...(() => { const c = getCreator(3); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-029',
    title: 'Waterfall Wonder',
    description: 'Silky smooth waterfall captured with long exposure.',
    mediaUrl: 'https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?w=800&q=80',
    mediaType: 'image',
    price: 1.3,
    category: 'photography',
    tags: ['waterfall', 'long-exposure', 'nature', 'water'],
    ...(() => { const c = getCreator(4); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-030',
    title: 'Tokyo Nights',
    description: 'Vibrant nightlife of Tokyo streets.',
    mediaUrl: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&q=80',
    mediaType: 'image',
    price: 1.6,
    category: 'photography',
    tags: ['tokyo', 'night', 'urban', 'neon'],
    ...(() => { const c = getCreator(5); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-031',
    title: 'Butterfly Dreams',
    description: 'Stunning macro shot of a monarch butterfly.',
    mediaUrl: 'https://images.unsplash.com/photo-1452570053594-1b985d6ea890?w=800&q=80',
    mediaType: 'image',
    price: 0.85,
    category: 'photography',
    tags: ['butterfly', 'macro', 'nature', 'wildlife'],
    ...(() => { const c = getCreator(6); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-032',
    title: 'Venice Canals',
    description: 'Classic Venice canal scene at dawn.',
    mediaUrl: 'https://images.unsplash.com/photo-1514890547357-a9ee288728e0?w=800&q=80',
    mediaType: 'image',
    price: 1.7,
    category: 'photography',
    tags: ['venice', 'travel', 'architecture', 'water'],
    ...(() => { const c = getCreator(7); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-033',
    title: 'Storm Chaser',
    description: 'Dramatic thunderstorm with lightning strike.',
    mediaUrl: 'https://images.unsplash.com/photo-1461511669078-d46bf351cd6e?w=800&q=80',
    mediaType: 'image',
    price: 2.2,
    category: 'photography',
    tags: ['storm', 'lightning', 'dramatic', 'weather'],
    ...(() => { const c = getCreator(0); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-034',
    title: 'Lavender Fields',
    description: 'Endless purple lavender fields at sunset.',
    mediaUrl: 'https://images.unsplash.com/photo-1499002238440-d264edd596ec?w=800&q=80',
    mediaType: 'image',
    price: 1.0,
    category: 'photography',
    tags: ['lavender', 'fields', 'purple', 'nature'],
    ...(() => { const c = getCreator(1); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },

  // ============ MUSIC (13 items) ============
  {
    id: 'nft-035',
    title: 'Vinyl Dreams',
    description: 'Classic vinyl record collection artwork.',
    mediaUrl: 'https://images.unsplash.com/photo-1494232410401-ad00d5433cfa?w=800&q=80',
    mediaType: 'image',
    price: 0.5,
    category: 'music',
    tags: ['vinyl', 'retro', 'music', 'collection'],
    ...(() => { const c = getCreator(2); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-036',
    title: 'Electric Guitar Soul',
    description: 'Stunning electric guitar in dramatic lighting.',
    mediaUrl: 'https://images.unsplash.com/photo-1510915361894-db8b60106cb1?w=800&q=80',
    mediaType: 'image',
    price: 0.8,
    category: 'music',
    tags: ['guitar', 'rock', 'music', 'instrument'],
    ...(() => { const c = getCreator(3); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-037',
    title: 'DJ Turntables',
    description: 'Professional DJ setup with vibrant club lighting.',
    mediaUrl: 'https://images.unsplash.com/photo-1571266028243-e4733b0f0bb0?w=800&q=80',
    mediaType: 'image',
    price: 1.2,
    category: 'music',
    tags: ['DJ', 'electronic', 'club', 'turntable'],
    ...(() => { const c = getCreator(4); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-038',
    title: 'Piano Keys',
    description: 'Elegant piano keys in black and white.',
    mediaUrl: 'https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?w=800&q=80',
    mediaType: 'image',
    price: 0.6,
    category: 'music',
    tags: ['piano', 'classical', 'elegant', 'keys'],
    ...(() => { const c = getCreator(5); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-039',
    title: 'Saxophone Jazz',
    description: 'Golden saxophone with smooth jazz vibes.',
    mediaUrl: 'https://images.unsplash.com/photo-1511192336575-5a79af67a629?w=800&q=80',
    mediaType: 'image',
    price: 0.9,
    category: 'music',
    tags: ['saxophone', 'jazz', 'gold', 'music'],
    ...(() => { const c = getCreator(6); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-040',
    title: 'Drum Kit Power',
    description: 'Professional drum kit under stage lights.',
    mediaUrl: 'https://images.unsplash.com/photo-1519892300165-cb5542fb47c7?w=800&q=80',
    mediaType: 'image',
    price: 0.7,
    category: 'music',
    tags: ['drums', 'percussion', 'stage', 'rock'],
    ...(() => { const c = getCreator(7); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-041',
    title: 'Headphones Vibe',
    description: 'Premium headphones with neon glow.',
    mediaUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80',
    mediaType: 'image',
    price: 0.55,
    category: 'music',
    tags: ['headphones', 'audio', 'neon', 'tech'],
    ...(() => { const c = getCreator(0); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-042',
    title: 'Concert Crowd',
    description: 'Epic concert crowd with hands in the air.',
    mediaUrl: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800&q=80',
    mediaType: 'image',
    price: 1.1,
    category: 'music',
    tags: ['concert', 'crowd', 'live', 'energy'],
    ...(() => { const c = getCreator(1); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-043',
    title: 'Synthesizer Dreams',
    description: 'Vintage synthesizer with glowing controls.',
    mediaUrl: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=800&q=80',
    mediaType: 'image',
    price: 1.4,
    category: 'music',
    tags: ['synthesizer', 'electronic', 'vintage', 'synth'],
    ...(() => { const c = getCreator(2); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-044',
    title: 'Microphone Spotlight',
    description: 'Classic microphone under single spotlight.',
    mediaUrl: 'https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=800&q=80',
    mediaType: 'image',
    price: 0.65,
    category: 'music',
    tags: ['microphone', 'vocal', 'spotlight', 'performance'],
    ...(() => { const c = getCreator(3); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-045',
    title: 'Bass Guitar Groove',
    description: 'Sleek bass guitar with blue lighting.',
    mediaUrl: 'https://images.unsplash.com/photo-1516924962500-2b4b3b99ea02?w=800&q=80',
    mediaType: 'image',
    price: 0.75,
    category: 'music',
    tags: ['bass', 'guitar', 'groove', 'blue'],
    ...(() => { const c = getCreator(4); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-046',
    title: 'Music Studio',
    description: 'Professional recording studio setup.',
    mediaUrl: 'https://images.unsplash.com/photo-1598653222000-6b7b7a552625?w=800&q=80',
    mediaType: 'image',
    price: 1.8,
    category: 'music',
    tags: ['studio', 'recording', 'professional', 'production'],
    ...(() => { const c = getCreator(5); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-047',
    title: 'Cassette Nostalgia',
    description: 'Retro cassette tapes collection.',
    mediaUrl: 'https://images.unsplash.com/photo-1527150122806-f682d2fd8b09?w=800&q=80',
    mediaType: 'image',
    price: 0.45,
    category: 'music',
    tags: ['cassette', 'retro', 'nostalgia', '80s'],
    ...(() => { const c = getCreator(6); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },

  // ============ VIDEO (12 items) ============
  {
    id: 'nft-048',
    title: 'Cinema Experience',
    description: 'Classic movie theater with red velvet seats.',
    mediaUrl: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800&q=80',
    mediaType: 'image',
    price: 1.5,
    category: 'video',
    tags: ['cinema', 'theater', 'movies', 'classic'],
    ...(() => { const c = getCreator(7); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-049',
    title: 'Film Reel Memories',
    description: 'Vintage film reels and projector.',
    mediaUrl: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=800&q=80',
    mediaType: 'image',
    price: 0.9,
    category: 'video',
    tags: ['film', 'vintage', 'projector', 'cinema'],
    ...(() => { const c = getCreator(0); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-050',
    title: 'Camera Lens Art',
    description: 'Professional cinema camera lens close-up.',
    mediaUrl: 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=800&q=80',
    mediaType: 'image',
    price: 1.2,
    category: 'video',
    tags: ['camera', 'lens', 'cinema', 'professional'],
    ...(() => { const c = getCreator(1); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-051',
    title: 'Clapperboard Action',
    description: 'Movie clapperboard ready for action.',
    mediaUrl: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=800&q=80',
    mediaType: 'image',
    price: 0.7,
    category: 'video',
    tags: ['clapperboard', 'film', 'action', 'production'],
    ...(() => { const c = getCreator(2); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-052',
    title: 'Drone Cinematography',
    description: 'Professional drone capturing aerial footage.',
    mediaUrl: 'https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=800&q=80',
    mediaType: 'image',
    price: 2.1,
    category: 'video',
    tags: ['drone', 'aerial', 'cinematography', 'tech'],
    ...(() => { const c = getCreator(3); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-053',
    title: 'Video Editing Suite',
    description: 'Professional video editing workstation.',
    mediaUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800&q=80',
    mediaType: 'image',
    price: 1.6,
    category: 'video',
    tags: ['editing', 'workstation', 'production', 'professional'],
    ...(() => { const c = getCreator(4); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-054',
    title: 'Streaming Setup',
    description: 'Modern streaming and content creation setup.',
    mediaUrl: 'https://images.unsplash.com/photo-1598550476439-6847785fcea6?w=800&q=80',
    mediaType: 'image',
    price: 1.3,
    category: 'video',
    tags: ['streaming', 'content', 'setup', 'modern'],
    ...(() => { const c = getCreator(5); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-055',
    title: 'Green Screen Magic',
    description: 'Professional green screen studio setup.',
    mediaUrl: 'https://images.unsplash.com/photo-1576633587382-13ddf37b1fc1?w=800&q=80',
    mediaType: 'image',
    price: 1.1,
    category: 'video',
    tags: ['green-screen', 'studio', 'VFX', 'production'],
    ...(() => { const c = getCreator(6); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-056',
    title: 'Vintage Television',
    description: 'Retro TV set with static screen.',
    mediaUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=80',
    mediaType: 'image',
    price: 0.6,
    category: 'video',
    tags: ['TV', 'vintage', 'retro', 'static'],
    ...(() => { const c = getCreator(7); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-057',
    title: 'Film Strip',
    description: '35mm film strip with frames.',
    mediaUrl: 'https://images.unsplash.com/photo-1440404653325-ab127d49abc1?w=800&q=80',
    mediaType: 'image',
    price: 0.8,
    category: 'video',
    tags: ['film', '35mm', 'strip', 'analog'],
    ...(() => { const c = getCreator(0); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-058',
    title: 'Director Chair',
    description: 'Iconic director chair on film set.',
    mediaUrl: 'https://images.unsplash.com/photo-1524712245354-2c4e5e7121c0?w=800&q=80',
    mediaType: 'image',
    price: 0.95,
    category: 'video',
    tags: ['director', 'chair', 'film', 'set'],
    ...(() => { const c = getCreator(1); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-059',
    title: 'VHS Collection',
    description: 'Nostalgic VHS tape collection.',
    mediaUrl: 'https://images.unsplash.com/photo-1594909122845-11baa439b7bf?w=800&q=80',
    mediaType: 'image',
    price: 0.5,
    category: 'video',
    tags: ['VHS', 'retro', 'collection', 'nostalgia'],
    ...(() => { const c = getCreator(2); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },

  // ============ GAMES (12 items) ============
  {
    id: 'nft-060',
    title: 'Cyber Genesis Avatar',
    description: 'A futuristic character design for the Cyber Genesis gaming universe.',
    mediaUrl: 'https://images.unsplash.com/photo-1635322966219-b75ed372eb01?w=800&q=80',
    mediaType: 'image',
    price: 5.2,
    category: 'games',
    tags: ['gaming', 'character', 'cyberpunk', 'avatar'],
    ...(() => { const c = getCreator(3); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-061',
    title: 'Metaverse Land Plot #247',
    description: 'Prime virtual real estate in the metaverse.',
    mediaUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    mediaType: 'image',
    price: 15.0,
    category: 'games',
    tags: ['metaverse', 'land', 'virtual', 'real-estate'],
    ...(() => { const c = getCreator(4); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-062',
    title: 'Ancient Warriors Collection',
    description: 'Legendary warrior characters from ancient realms.',
    mediaUrl: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=800&q=80',
    mediaType: 'image',
    price: 4.2,
    category: 'games',
    tags: ['warriors', 'fantasy', 'RPG', 'characters'],
    ...(() => { const c = getCreator(5); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-063',
    title: 'Gaming Setup RGB',
    description: 'Ultimate RGB gaming setup.',
    mediaUrl: 'https://images.unsplash.com/photo-1593305841991-05c297ba4575?w=800&q=80',
    mediaType: 'image',
    price: 2.8,
    category: 'games',
    tags: ['gaming', 'RGB', 'setup', 'PC'],
    ...(() => { const c = getCreator(6); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-064',
    title: 'Retro Arcade',
    description: 'Classic arcade cabinet artwork.',
    mediaUrl: 'https://images.unsplash.com/photo-1511882150382-421056c89033?w=800&q=80',
    mediaType: 'image',
    price: 1.5,
    category: 'games',
    tags: ['arcade', 'retro', 'gaming', 'classic'],
    ...(() => { const c = getCreator(7); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-065',
    title: 'VR Headset Future',
    description: 'Next-gen VR headset design.',
    mediaUrl: 'https://images.unsplash.com/photo-1622979135225-d2ba269cf1ac?w=800&q=80',
    mediaType: 'image',
    price: 3.5,
    category: 'games',
    tags: ['VR', 'virtual-reality', 'future', 'tech'],
    ...(() => { const c = getCreator(0); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-066',
    title: 'Game Controller Neon',
    description: 'Gaming controller with neon lights.',
    mediaUrl: 'https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=800&q=80',
    mediaType: 'image',
    price: 1.2,
    category: 'games',
    tags: ['controller', 'neon', 'gaming', 'console'],
    ...(() => { const c = getCreator(1); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-067',
    title: 'Pixel Art Hero',
    description: 'Classic pixel art game character.',
    mediaUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&q=80',
    mediaType: 'image',
    price: 0.9,
    category: 'games',
    tags: ['pixel', 'art', 'retro', 'character'],
    ...(() => { const c = getCreator(2); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-068',
    title: 'Esports Arena',
    description: 'Professional esports competition arena.',
    mediaUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&q=80',
    mediaType: 'image',
    price: 6.5,
    category: 'games',
    tags: ['esports', 'arena', 'competition', 'professional'],
    ...(() => { const c = getCreator(3); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-069',
    title: 'Gaming Keyboard RGB',
    description: 'Mechanical gaming keyboard with RGB.',
    mediaUrl: 'https://images.unsplash.com/photo-1595225476474-87563907a212?w=800&q=80',
    mediaType: 'image',
    price: 1.0,
    category: 'games',
    tags: ['keyboard', 'mechanical', 'RGB', 'gaming'],
    ...(() => { const c = getCreator(4); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-070',
    title: 'Space Battle Scene',
    description: 'Epic space battle from sci-fi game.',
    mediaUrl: 'https://images.unsplash.com/photo-1614732414444-096e5f1122d5?w=800&q=80',
    mediaType: 'image',
    price: 4.8,
    category: 'games',
    tags: ['space', 'battle', 'sci-fi', 'epic'],
    ...(() => { const c = getCreator(5); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-071',
    title: 'Fantasy Castle',
    description: 'Majestic castle from fantasy game world.',
    mediaUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&q=80',
    mediaType: 'image',
    price: 7.2,
    category: 'games',
    tags: ['fantasy', 'castle', 'medieval', 'game'],
    ...(() => { const c = getCreator(6); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },

  // ============ COLLECTIBLES (12 items) ============
  {
    id: 'nft-072',
    title: 'Diamond Gemstone',
    description: 'Brilliant cut diamond collectible.',
    mediaUrl: 'https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=800&q=80',
    mediaType: 'image',
    price: 10.5,
    category: 'collectibles',
    tags: ['diamond', 'gem', 'luxury', 'rare'],
    ...(() => { const c = getCreator(7); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-073',
    title: 'Vintage Watch',
    description: 'Classic luxury timepiece collectible.',
    mediaUrl: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=800&q=80',
    mediaType: 'image',
    price: 8.2,
    category: 'collectibles',
    tags: ['watch', 'vintage', 'luxury', 'time'],
    ...(() => { const c = getCreator(0); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-074',
    title: 'Gold Coin Collection',
    description: 'Rare gold coins from around the world.',
    mediaUrl: 'https://images.unsplash.com/photo-1610375461246-83df859d849d?w=800&q=80',
    mediaType: 'image',
    price: 5.5,
    category: 'collectibles',
    tags: ['gold', 'coins', 'rare', 'collection'],
    ...(() => { const c = getCreator(1); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-075',
    title: 'Crystal Skull',
    description: 'Mysterious crystal skull artifact.',
    mediaUrl: 'https://images.unsplash.com/photo-1518709414768-a88981a4515d?w=800&q=80',
    mediaType: 'image',
    price: 12.0,
    category: 'collectibles',
    tags: ['crystal', 'skull', 'artifact', 'mysterious'],
    ...(() => { const c = getCreator(2); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-076',
    title: 'Antique Key',
    description: 'Ornate antique skeleton key.',
    mediaUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    mediaType: 'image',
    price: 2.3,
    category: 'collectibles',
    tags: ['antique', 'key', 'vintage', 'ornate'],
    ...(() => { const c = getCreator(3); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-077',
    title: 'Rare Stamp',
    description: 'Valuable philatelic collectible.',
    mediaUrl: 'https://images.unsplash.com/photo-1584727638096-042c45049ebe?w=800&q=80',
    mediaType: 'image',
    price: 3.8,
    category: 'collectibles',
    tags: ['stamp', 'rare', 'philately', 'vintage'],
    ...(() => { const c = getCreator(4); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-078',
    title: 'Porcelain Vase',
    description: 'Exquisite Chinese porcelain vase.',
    mediaUrl: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=800&q=80',
    mediaType: 'image',
    price: 6.7,
    category: 'collectibles',
    tags: ['porcelain', 'vase', 'chinese', 'antique'],
    ...(() => { const c = getCreator(5); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-079',
    title: 'Vintage Camera',
    description: 'Classic film camera collectible.',
    mediaUrl: 'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=800&q=80',
    mediaType: 'image',
    price: 2.9,
    category: 'collectibles',
    tags: ['camera', 'vintage', 'film', 'classic'],
    ...(() => { const c = getCreator(6); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-080',
    title: 'Ancient Artifact',
    description: 'Mysterious ancient civilization relic.',
    mediaUrl: 'https://images.unsplash.com/photo-1599707367072-cd6ada2bc375?w=800&q=80',
    mediaType: 'image',
    price: 15.5,
    category: 'collectibles',
    tags: ['ancient', 'artifact', 'relic', 'history'],
    ...(() => { const c = getCreator(7); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-081',
    title: 'Luxury Pen',
    description: 'Premium fountain pen collectible.',
    mediaUrl: 'https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=800&q=80',
    mediaType: 'image',
    price: 4.1,
    category: 'collectibles',
    tags: ['pen', 'luxury', 'fountain', 'writing'],
    ...(() => { const c = getCreator(0); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-082',
    title: 'Compass Navigator',
    description: 'Antique brass navigation compass.',
    mediaUrl: 'https://images.unsplash.com/photo-1490730141103-6cac27abb37f?w=800&q=80',
    mediaType: 'image',
    price: 3.2,
    category: 'collectibles',
    tags: ['compass', 'navigation', 'brass', 'antique'],
    ...(() => { const c = getCreator(1); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
  {
    id: 'nft-083',
    title: 'Ruby Gemstone',
    description: 'Stunning deep red ruby collectible.',
    mediaUrl: 'https://images.unsplash.com/photo-1551122087-f99a4f1be49c?w=800&q=80',
    mediaType: 'image',
    price: 9.8,
    category: 'collectibles',
    tags: ['ruby', 'gem', 'red', 'precious'],
    ...(() => { const c = getCreator(2); return { creatorName: c.name, creatorUsername: c.username, creatorAvatar: c.avatar, ownerName: c.name, ownerUsername: c.username, ownerAvatar: c.avatar }; })(),
    likes: randomLikes(),
    views: randomViews(),
  },
];

// Get top sellers (highest priced)
export const topSellers = [...sampleNFTs]
  .sort((a, b) => b.price - a.price)
  .slice(0, 6);

// Get by category
export const getByCategory = (category: string) =>
  sampleNFTs.filter((nft) => nft.category === category);

// Get featured (random selection)
export const featuredNFTs = sampleNFTs.slice(0, 8);